apiVersion: v2
name: metrics-proxy
description: Lightweight proxy that caches Thanos metrics and serves them as JSON for joluc.de
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://github.com/joluc/metrics-proxy
sources:
  - https://github.com/joluc/metrics-proxy
keywords:
  - prometheus
  - thanos
  - metrics
  - proxy
maintainers:
  - name: joluc
    url: https://github.com/joluc
