apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metrics-proxy.fullname" . }}
  labels:
    {{- include "metrics-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    metrics:
    {{- toYaml .Values.config.metrics | nindent 6 }}
